# Generated by Django 5.1 on 2024-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Shounen'), (2, 'Isekai'), (3, 'Shoujo'), (4, 'Seinen'), (5, 'Others')])),
                ('release_date', models.DateField()),
                ('seasons', models.IntegerField()),
                ('total_episodes', models.IntegerField()),
                ('dttm_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
