# Generated by Django 5.0 on 2024-08-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_anime_release_date_alter_anime_seasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Shounen'), (2, 'Isekai'), (3, 'Shoujo'), (4, 'Seinen'), (5, 'Action'), (6, 'Thriller'), (7, 'Adventure'), (8, 'Horror'), (9, 'Fantasy'), (10, 'Mecha'), (11, 'Others')]),
        ),
    ]
